### ISSUE TITLE
config

### ISSUE THREAD

**Issue by greatwebber** [smertcanyilmaz/react_real_estate_app#1]
hello pls i need a guide how i can config this project, thanks. very urgent

**Comment by smertcanyilmaz** [comment]
Hello, what exactly is the problem? My project is a standard Vite project
and you can do this the same way you set up and start all your Vite
projects.

**Comment by greatwebber** [comment]
m new to vite .. pls i need a guide to update and configure the database

**Comment by greatwebber** [comment]
did i have to config the firebase ?

**Comment by smertcanyilmaz** [comment]
> did i have to config the firebase ?

If you want to develop a full stack project using firebase, of course you need to install firebase in your project. You can use firebase documentation or YouTube for this. On the other hand, if you want to start a vite project, you can check this link: https://vitejs.dev/guide/

**Comment by greatwebber** [comment]
did you use firebase for the backend or what application is been used for the backend

**Comment by smertcanyilmaz** [comment]
> did you use firebase for the backend or what application is been used for the backend 
> 
> 

Yes, I used firebase for the backend. In this project, all crud and auth transactions occur through firebase.

**Comment by greatwebber** [comment]
alright .. so all i need to do is to connect the database right ?

**Comment by smertcanyilmaz** [comment]
yes

**Comment by greatwebber** [comment]
alright .. i will check this out ..Thanks a lot

**Comment by smertcanyilmaz** [comment]
> alright .. i will check this out ..Thanks a lot 

You're welcome
